### ISSUE TITLE
Images in docs have incorrect URL's

### ISSUE THREAD

**Issue by chrisb2** [upsidedownlabs/BioAmp-EXG-Pill#23]
For example in [electromyography.md](https://github.com/upsidedownlabs/BioAmp-EXG-Pill/blob/main/docs/electromyography.md) the first image has a URL of [https://github.com/upsidedownlabs/BioAmp-EXG-Pill/blob/main/docs/%20images/EMG/bioamp-exg-pill-emg-wave.jpg](https://github.com/upsidedownlabs/BioAmp-EXG-Pill/blob/main/docs/%20images/EMG/bioamp-exg-pill-emg-wave.jpg) which has a space (%20) in front of the _images_ directory, without this space the URL would be correct.

Chris

**Comment by lorforlinux** [comment]
Hey @chrisb2, The issue has been resolved.
Can you please check and confirm?

**Comment by chrisb2** [comment]
Sorry looking through the Readmes I can see remaining broken links and the embedded videos are just showing as iframes in the rendered markdown.

**Comment by lorforlinux** [comment]
Ohh okay, sorry for the inconvenience caused. 
Can you please point me to that broken link?

**Comment by chrisb2** [comment]
Broken video iframes in:
https://github.com/upsidedownlabs/BioAmp-EXG-Pill/blob/main/docs/electromyography.md
https://github.com/upsidedownlabs/BioAmp-EXG-Pill/blob/main/docs/electrocardiography.md
https://github.com/upsidedownlabs/BioAmp-EXG-Pill/blob/main/docs/electroencephalography.md
https://github.com/upsidedownlabs/BioAmp-EXG-Pill/blob/main/docs/electrooculography.md

Broken image links in:
https://github.com/upsidedownlabs/BioAmp-EXG-Pill/blob/main/docs/electrocardiography.md
