### ISSUE TITLE
Blink detection is broken.

### ISSUE THREAD

**Issue by padmalaya-rawal** [upsidedownlabs/BioAmp-EXG-Pill#6]
Hey, thanks for providing such a great open source project. But just for your kind information the blink detection code is broken. : )

**Comment by padmalaya-rawal** [comment]
Hey, I tried the code once again and its working, that was my mistake. Closing the issue 👍🏻

**Comment by lorforlinux** [comment]
Hey @padmalaya-rawal, Thank you for your generous support.
