### ISSUE TITLE
[QUESTION] Bioelectrical impedance analysis (BIA) 

### ISSUE THREAD

**Issue by dmazzella** [upsidedownlabs/BioAmp-EXG-Pill#7]
Hi folks,
is possible to use BopAmp for bioimpecence analysis?

Thanks,
D.

**Comment by lorforlinux** [comment]
Hey @dmazzella, that is totally possible. BioAmp EXG Pill is basically a sophisticated amplifier for recording signals from the body. You can use the technique used in the [OpenBCI ganglion](https://github.com/OpenBCI/Ganglion_Hardware_Design_Files/blob/master/Ganglion_SCH.pdf) board for BIA.

**Comment by dmazzella** [comment]
Can you provide an example of use with BioAmp EXG Pill?

Thanks,
D.

**Comment by lorforlinux** [comment]
Hey @dmazzella, Please see the image below for a basic BIA setup. You can create a similar setup where BioAmp EXG Pill be the voltage measuring device connected to an ADC, then you create a constant current source. With these 2 building blocks in place, you have your own BIA setup ready. Also, checkout the [OpenBCI ganglion schematic](https://github.com/OpenBCI/Ganglion_Hardware_Design_Files/blob/master/Ganglion_SCH.pdf) to see how they are using INA and DAC for impedance detection. I hope this helps :)

![](https://www.researchgate.net/profile/Ehab-Mohamed-5/publication/301737400/figure/fig1/AS:366654107209728@1464428559601/Schematic-representation-of-the-bioelectric-impedance-analysis-BIA-measuring-technique.png)
Source: https://www.researchgate.net/figure/Schematic-representation-of-the-bioelectric-impedance-analysis-BIA-measuring-technique_fig1_301737400
